---
author: Hristo Genev
culture: bg-BG
date-format: yyyy/MM/dd

request:
  debug: false
  url: https://www.axn-bulgaria.com/programa/ajax/axnbg/data/listings/true/${date}
    
programs:
  locator: li.listing
    
elements:
  - name: start
    locator: .date

  - name: _meta
    locator: .meta

  - name: title
    language: bg
    locator: .title
    operations:
      - name: beautify
        hook: after
      - name: append
        hook: after
        arguments: [ ", ${_meta}" ]
        conditions: [ value-not-empty ]
  - name: category
    language: en
    locator: .genre

  - name: icon
    locator: img
    attribute: src

  - name: _detailsurl
    locator: .title a
    attribute: href

# program-details:
#   request:
#     url: https://www.axn-bulgaria.com${_detailsurl}
  
#   elements:
#     - name: desc
#       enabled: false
#       locator: .pane-title + .pane-content p

delay-between-requests: 500