---
id: b1b.tv
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: https://b1b.tv/%d0%bf%d1%80%d0%be%d0%b3%d1%80%d0%b0%d0%bc%d0%b0/
  cache-lifetime: 1

programs:
  locator: tr
  exclude-first: 1
  debug: false
  operations:
    - name: remove-before
      hook: before
      arguments: [ "${date.format(d MMMM)}", false ]
      debug: false
    - name: remove-after
      hook: before
      arguments: [ "${date.addDays(1).format(d MMMM)}", false ]
      debug: false

elements:
  - name: start
    locator: td:nth-of-type(3)
    debug: false
  - name: _category
    locator: td:nth-of-type(1)
    operations:
      - name: capitalize
        hook: after
  - name: title
    lang: bg
    locator: td:nth-of-type(2)
    operations: 
      - name: prepend
        hook: after
        arguments: [ "${_category}: " ]
        operations: [ argument-not-empty ]