author: Hristo Genev
culture: bg-BG
date-format: yyyy-MM-dd

request:
  url: https://bstv.bg/programa/${date}

programs:
  debug: true
  locator: .schedule-list p
    
elements:
  - name: start
    debug: true
    time-format: HH.mm
    operations:
    - hook: after
      name: regex-extract
      arguments: [ '(\d\d\.\d\d)' ]
            
  - name: title
    debug: true
    language: bg
    operations:
    - hook: after
      name: regex-remove
      arguments: [ '(\d\d\.\d\d\s*)' ]
    - hook: after
      name: remove
      arguments: [ '„', '“' ]