---
author: Hristo Genev
culture: bg-BG

# Use predefined list of date values instead of real dates
date-format: list

# The content of the predefined list of dates that will be used
date-list: [ ponedelnik, vtornik, sryada, chetvartak, petuk, sabota, nedelya ]

# The date-list-type can be absolute or relative. The default value if omitted is relative
# Relative means, that values from date-list will be always used from the first value on
# Absolute means, that values from date-list will be used as per the current day of the week index
# i.e. if today is Tuesday (the second day of the week), the grabber will use the second value from the date-list.
# when it starts grabbing programs for the 3-rd day of the week, the 3-rd value will be used and so forth.
date-list-type: absolute

# This property means there are only programs for a single week.
# Usually the weekly schedule is updated once a week every Monday.
# So, if you grab on Monday you'll have program for 7 days, but if 
# you grab on Sunday you will have programs only for 1 day since
# the programs for the other days will already be old and not updated yet.
# When using this parameter, you tell the tool to grab only 
# programs within this week. If you run the grabber on Sunday it will
# only grab 1 day and it will ignore the setting days-ahead if it is more than 1
single-week: true

request:
  url: https://codehealthplay.bg/programa/${date}
  operations:
    # We add this operation which will verify if the date is found in today's page
    # If not found, it means the page has expired content so we'll skip grabbing it
    - name: validate-text-exists
      hook: after
      arguments: [ "(${date.format(dd.MM)}) - Code Health TV" ]
      on-failure: quit-daily-grabbing
      debug: false

programs:
  locator: .jet-listing-grid__item
  debug: false

elements:
  - name: start
    debug: false
    time-format: H:mm
    locator-strategy: xpath
    locator: (div//div[@class="jet-listing-dynamic-field__content"])[1]

  - name: title
    debug: false
    locator-strategy: xpath
    locator: (div//div[@class="jet-listing-dynamic-field__content"])[2]

  - name: desc
    debug: false
    locator-strategy: xpath
    locator: (div//div[@class="jet-listing-dynamic-field__content"])[3]