---
id: localhost.multiday
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: https://localhost/?channelId=${channelId}&date=${date}/${channelUrl}
  date-format: yyyy-MM-dd
  cache-priority: 3
  encoding: windows-1251

programs:     
  debug: true
  method: csspath
  locator: .b5,.tv_line,.clearfix
  
  operations:
    - name: remove-before
      hook: before
      arguments: [<div id="full_program">, true]
    - name: remove-after
      hook: before
      arguments: [ </div><div class="c"></div>", true ]


elements:
  - name: start
    locator: .info
  - name: title
    locator: .ttl
    language: bg

channel-parameters:
  channel1.id:
     channelId: 1
     channelUrl: program-for-a-single-day-mixed.html
     locator: .b5,.tv_line,.clearfix

  channel2.id:
     channelId: 2
     channelUrl: program-for-a-single-day-mixed.html
     locator: .b5,.tv_line,.clearfix
          
  channel3.id:
    channelId: 3
    channelUrl: program-for-2-days.html
    locator: .b5,.tv_line,.clearfix
      
  channel4.id:
    channelId: 4
    channelUrl: program-for-2-days.html
    locator: .b5,.tv_line,.clearfix

  channel.berlin:
    channelId: channel.berlin
    channelUrl: program-for-2-days.html
    locator: .b5,.tv_line,.clearfix
    timezone": Europe/Berlin