---
id: localhost.timezone
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG
timezone: Europe/Berlin

request:
  url: https://localhost/?channelId=${channelId}&date=${date}/${channelUrl}
  date-format: yyyy-MM-dd
  cache-priority: 3
  encoding: windows-1251

programs:     
  debug: true
  method: csspath
  locator: .b5,.tv_line,.clearfix
  
  operations:
    - name: remove-before
      hook: before
      debug: true
      arguments: [<div id="full_program">, true]
    - name: remove-after
      hook: before
      arguments: [ </div><div class="c"></div>", true ]


elements:
  - name: start
    locator: .info
  - name: title
    locator: .ttl
    language: en
  - name: detailsUrl
    debug: true
    locator: a
    attribute: href
    operations:
      - name: prepend
        hook: after
        debug: true
        arguments: 
          - http://localhost/program/channel/${channelId}/
        conditions:
          - value-not-empty

program-details:
  request:
    url: ${detailsUrl}
    cache-priority: 3
    debug: true

  elements:
    - name: desc
      locator: "#desc"
      operations:
      - name: beautify
        hook: after

channel-parameters:
  channel1.id:
    channelId: 1
    channelUrl: program-for-a-single-day.html 
  channel2.id:
    channelId: '2'
    channelUrl: program-for-a-single-day.html
    locator: ".b5,.tv_line,.clearfix"
  channel3.id:
    channelId: '3'
    channelUrl: program-for-2-days.html
    locator": .b5,.tv_line,.clearfix"
  channel4.id:
    channelId: '4'
    channelUrl: program-for-2-days.html
    locator: .b5,.tv_line,.clearfix
  channel.berlin:
    channelId: channel.berlin
    channelUrl: program-for-2-days.html
    locator: .b5,.tv_line,.clearfix
    timezone: Europe/Berlin  