---
id: localhost.html
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: https://localhost/?channelId=${channelId}&date=${date}/${channelUrl}
  cache-priority: 3
  date-format: yyyy-MM-dd

programs:
  debug: false
  locator-strategy: csspath
  locator: .b5,.tv_line,.clearfix
  operations:
    - name: remove-before
      hook: before 
      debug: false
      arguments: [ <div id="full_program">, true ]
    - name: remove-after
      hook: before 
      arguments: [ </div><div class="c"></div>, true]

elements:  
  - name: start
    locator: .info

  - name: title
    language: bg
    locator: .ttl

  - name: detailsUrl
    debug: false
    locator: a
    attribute: href
    operations:
      - name: prepend
        hook: after
        debug: false
        arguments: [ 'http://localhost/program/channel/${channelId}/' ]
        conditions: [ value-not-empty ]

program-details:
  request:
    url: ${detailsUrl}
    cache-priority: 3
    debug: false

  elements:
    - name: desc
      locator: '#desc'
      operations:
        - name: beautify
          hook: after
    - name: actor
      locator: .actor
      max: 3
    - name: director
      locator: .director
      max: 3

channel-parameters:
  channel1.id:
    channelId: 1
    channelUrl: program-for-a-single-day.html
  channel2.id:
    channelId: 2
    channelUrl: program-for-a-single-day.html
  channel3.id:
    channelId: '3'
    channelUrl: program-for-2-days.html
  channel4.id:
    channelId: '4'
    channelUrl: program-for-2-days.html
  channel5.id:
    channelId: 5
    channelUrl: program-for-half-day.html
  channel6.id:
    channelId: 6
    channelUrl: program-for-half-day.html
  channel.berlin:
    channelId: channel.berlin
    channelUrl: program-for-a-single-day.html
    timezone: Europe/Berlin  