---
id: localhost.json
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: https://localhost/?channelId=${channelId}&date=${date}/${channelUrl}
  date-format: yyyy-MM-dd
  debug: false
    
programs:
  locator-strategy: jsonpath
  locator: programs[:]

elements:
  - name: start
    debug: false
    locator: start
  - name: title  
    debug: false
    language: bg
    locator: title
  - name: title
    language: en
    debug: false
    locator: english-title
  - name: detailsUrl
    locator: details

program-details:
  request:
    url: https://localhost/${detailsUrl}

  elements:
    - name: desc
      language: bg
      locator: desc
    - name: actor
      locator: actor[:].name
      max: 3
    - name: date
      enabled: true
      locator: dateCreated
    - name: icon
      locator-strategy: jsonpath
      locator: image[0].url      
    - name: director
      locator: director[:].name
      
channel-parameters: 
  channel1.id:
    channelId: 1
    channelUrl: program-for-a-single-day.json
  channel2.id:
    channelId: 2
    channelUrl: program-for-a-single-day.json
  channel3.id:
    channelId: 3
    channelUrl: program-for-2-days.json
  channel4.id:
    channelId: 4
    channelUrl: program-for-2-days.json
  channel5.id:
    channelId: 5
    channelUrl: program-for-a-single-day.json
  channel6.id:
    channelId: 6
    channelUrl: program-for-a-single-day.json