---
id: localhost.json.random
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: https://localhost/?channelId=${channelId}&date=${date}/${channelUrl}
  date-format: yyyy-MM-dd
  cache-priority: 3
  debug: true
    
programs:
  locator-strategy: jsonpath
  locator: programs[:]
  ordered: false

elements:
  - name: start
    debug: true
    locator: startTime
    time-format: o
  - name: title  
    debug: true
    language: bg
    locator: title

channel-parameters: 
  channel1.id:
    channelId: 1
    channelUrl: random-programs-for-a-single-day.json