---
id: localhost.json
enabled: true
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: https://localhost/?channelId=${channelId}&date=${date}/${channelUrl}
  date-format: yyyy-MM-dd
  debug: true
    
programs:
  locator-strategy: jsonpath
  locator: programs[:]

elements:
  - name: start
    debug: true
    locator: startTime
    time-format: o
  - name: title  
    debug: true
    language: bg
    locator: title

channel-parameters: 
  channel1.id:
    channelId: 1
    channelUrl: program-for-a-single-day.json
  channel2.id:
    channelId: 2
    channelUrl: program-for-a-single-day.json
  channel3.id:
    channelId: 3
    channelUrl: program-for-2-days.json
  channel4.id:
    channelId: 4
    channelUrl: program-for-2-days.json