---
id: moviestar.bg
version: 1.0
author: Hristo Genev
culture: bg-BG

request:
  url: http://moviestar.bg/?rhc_action=get_calendar_events&post_type[]=events&start=${date}&end=${date.addDays(1).format(unix)}&rhc_shrink=0&view=agendaDay
  cache-priority: 3
  encoding: utf-8
  date-format: unix
  
programs:
  ordered: false
  locator-strategy: jsonpath
  locator: $.EVENTS[?(@.fc_rdate =~ /${date.format(yyyyMMdd)}/)]
  
elements:
  - name: title
    locator: title

  - name: start
    locator: fc_rdate
    time-format: yyyyMMddTHHmm
    operations: 
    - name: regex-extract
      debug: true
      hook: after-extract
      arguments: 
        - .*?(${date.format(yyyyMMdd)}T\d\d\d\d)

  - name: desc
    ignore-previous-parsing: true
    language: bg
    locator: description

  - name: icon
    locator: image[0]

  - name: detailsUrl
    locator: url
  
program-details:
  enabled: false
  request:
    url: ${detailsUrl}

  elements:
  - name: desc
    locator: .fe-extrainfo-value