---
version: 1.0
author: Hristo Genev
timezone: Europe/Madrid
locator-strategy: jsonpath
date-format: yyyy-MM-dd

request:
  url: https://www.movistarplus.es/programacion-tv/${channelId}/${date}
  debug: false
  operations: 
    - name: remove-before
      hook: after
      arguments: [ "<script type=\"application/ld+json\">", true]
    - name: remove-after
      hook: after
      arguments: [ "</script>", true]
    
programs:
  debug: false
  locator: $.itemListElement[:]

elements:
  - name: start
    locator: item.startDate
    time-format: o
  - name: title  
    locator: item.name
  - name: stop
    locator: item.endDate
    time-format: o
      
channel-parameters:
  tve.es:
    channelId: TVE
  movistardeportes2.es:
    channelId: ARTHUR
  ligadecampeones.mplus.es:
    channelId: CHAPIO
  deportes.mplus.es:
    channelId: CPDEP
  telesur.es:
    channelId: TLESUR
  movistargolf.es:
    channelId: GOLF+