---
version: 1.0
author: Hristo Genev

date-parameter:
  format: list
  list: [ 0,1,2,3,4,5,6 ]

# This single-week property means there are only programs for a single week.
# Usually the weekly schedule is updated once a week every Monday.
# So, if you grab on Monday you'll have program for 7 days, but if 
# you grab on Sunday you will have programs only for 1 day since
# the programs for the other days will already be old and not updated yet.
# When using this parameter, you tell the tool to grab only 
# programs within this week. If you run the grabber on Sunday it will
# only grab 1 day and it will ignore the setting days-ahead if it is more than 1
single-week: true

request:
  url: https://see.bg/tv-programa

programs:
  locator: '#sched-${date} div'

elements:

  - name: start
    locator: .time

  - name: subtitle
    locator: .content

  - name: title
    locator: .title    
    operations:
      - name: append
        hook: after
        arguments: [ ' - ${subtitle}' ]
        conditions: [ argument-not-empty ]

