---
author: Hristo Genev
culture: bg-BG
date-format: dd

request:
  url: https://sportal.bg/tv-schedule?view=tv

programs:
  locator: .tv-program__row
    
elements:
  - name: start
    time-format: HH:mm
    locator: em    

  - name: title
    lang: bg
    locator: strong
    operations:
    - hook: after
      name: beautify