author: Hristo Genev
culture: sr-Latn-RS
timezone: Europe/Belgrade
locator-strategy: csspath
date-format: yyyy-MM-dd

request:
  url: https://www.tvarenasport.${topdomain}/tv-scheme/${date}
  debug: false

programs:
  locator: .tv-scheme-slider-item:nth-of-type(${channelId}) .slider-content
  debug: true

elements:
  - name: start
    locator: div.slider-content-header > span:nth-child(1)
    debug: true

  - name: sportType
    debug: true
    locator: div.slider-content-header > span:nth-child(2)
    operations:
      - name: append
        hook: after
        arguments: [ ": " ]
        conditions: [ value-not-empty ]
    
  - name: title  
    debug: true
    locator: p
    language: sr
    operations:
      - name: prepend
        hook: after
        arguments: ["${sportType}"]
        conditions: 
          - argument-not-empty
          - argument-not-contain-value

  - name: category
    enabled: true
    locator: .category

      
channel-parameters:
  arenasportpremium1.sr:
    topdomain: com 
    channelId: 1
  arenasportpremium2.sr:
    topdomain: com 
    channelId: 2
  arenasportpremium3.sr:
    topdomain: com
    channelId: 3
  arenasport1.sr:
    topdomain: com 
    channelId: 4
  arenasport2.sr:
    topdomain: com 
    channelId: 5
  arenasport3.sr:
    topdomain: com
    channelId: 6
  arenasport4.sr:
    topdomain: com
    channelId: 7
  arenasport5.sr:
    topdomain: com
    channelId: 8
  arenasport6.sr:
    topdomain: com
    channelId: 9
  arenasport7.sr:
    topdomain: com
    channelId: 10
  arenasport8.sr:
    topdomain: com
    channelId: 11
  arenasport9.sr:
    topdomain: com
    channelId: 12
  arenasport10.sr:
    topdomain: com
    channelId: 13

  arenasport1.hr:
    topdomain: hr
    channelId: 380
  arenasport2.hr:
    topdomain: hr 
    channelId: 381
  arenasport3.hr:
    topdomain: hr
    channelId: 382
  arenasport4.hr:
    topdomain: hr
    channelId: 383
  arenasport5.hr:
    topdomain: hr
    channelId: 384
  arenasport6.hr:
    topdomain: hr
    channelId: 1175
  arenasport7.hr:
    topdomain: hr
    channelId: 1291
  arenasport8.hr:
    topdomain: hr
    channelId: 1292
  arenasport9.hr:
    topdomain: hr
    channelId: 1293
  arenasport10.hr:
    topdomain: hr
    channelId: 1294