---
author: Hristo Genev
culture: Ru-ru
date-format: yyyy-MM-dd


request:
  url: https://tv.yandex.ru/channel/${channelId}?date=${date}
    
programs:
  locator-strategy: csspath
  locator: .channel-schedule__event
  #debug: true

elements: 
  - name: title
    language: ru
    locator: .channel-schedule__text
  - name: start
    locator: .channel-schedule__time
    debug: false
  - name: desc
    enabled: false
    locator: program.description


channel-parameters:
  ohotarybalka.ru:
    channelId: ohotnik-i-rybolov-69
  jivayapriroda.ru:
    channelId: jivaya-priroda-1090
  russiatoday.com:
    channelId: russia-today-70
  rtdoc.com:
    channelId: rt-doc-1258


# Used for extracting channel names and params from a page containing the list of available channels
#channel-extract-rules: 
#  url: https://ntvplus.ru/tv/ajax/tv?genre=all&date=now&tz=0&search=&channel=&offset=0
#  channel-name: 
#    locator: .channel-header--title a
#    property: text
    
#  channel-param: 
#    locator: .channel-header--title a
#    attribute: href